# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XtV <- function(X, V) {
    .Call(`_SpectralClustering_XtV`, X, V)
}

XB <- function(X, B) {
    .Call(`_SpectralClustering_XB`, X, B)
}

XXt <- function(X, Xt) {
    .Call(`_SpectralClustering_XXt`, X, Xt)
}

GSM <- function(A, sigma = 1) {
    .Call(`_SpectralClustering_GSM`, A, sigma)
}

GSMLocalScaling <- function(A, sigma) {
    .Call(`_SpectralClustering_GSMLocalScaling`, A, sigma)
}

Norm <- function(v) {
    .Call(`_SpectralClustering_Norm`, v)
}

redir <- function(file) {
    invisible(.Call(`_SpectralClustering_redir`, file))
}

resetredir <- function() {
    invisible(.Call(`_SpectralClustering_resetredir`))
}

CosineSimilarity <- function(X) {
    .Call(`_SpectralClustering_CosineSimilarity`, X)
}

Qm <- function(A) {
    .Call(`_SpectralClustering_Qm`, A)
}

